<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Git</string>
	<key>fileTypes</key>
	<array>
		<string>.git</string>
		<string>.gitignore</string>
		<string>.gitkeep</string>
		<string>.gitconfig</string>
		<string>.gitblame</string>
		<string>.gitcommit</string>
		<string>.gitgraph</string>
		<string>.gitattributes</string>
		<string>.gitmodules</string>
		<string>.git-blame</string>
		<string>.git-commit</string>
		<string>.git-graph</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.git</string>
			<string>source.gitignore</string>
			<string>source.gitkeep</string>
			<string>source.gitconfig</string>
			<string>source.gitblame</string>
			<string>source.gitcommit</string>
			<string>source.gitgraph</string>
			<string>source.gitattributes</string>
			<string>source.gitmodules</string>
			<string>source.git-blame</string>
			<string>source.git-commit</string>
			<string>source.git-graph</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.git</string>
</dict>
</plist>
